// Holds the SubGHz seed-recovery engine, its ABI header and the obfuscator's
// keep list to each other.
//
// The coupling these guard is unusual and easy to break silently. The engine is
// generated by an obfuscator that renames every identifier the source owns
// unless the name is in `keep.txt`. For most names a miss is loud - the engine
// would define a differently-spelled field than the header declares and the
// compile fails - but for `VBITS` and `NLF12` it is not, and those two are why
// this file exists.
//
// What it cannot see:
//
//  * Whether the engine computes the right thing. That is
//    `.github/scripts/check_faaccrack_engine.sh`.
//  * Whether the four FAACCRACK_MODE_* numbers still select the manufacturer
//    the header claims. The engine hard-codes them, so only an end-to-end
//    vector per mode can catch a renumbering - see BUILD_NOTES.md.
//  * Whether a dispatcher names the variants correctly. There is no dispatcher
//    yet; when there is, the assertion that its table matches
//    FAACCRACK_VARIANTS belongs in the same commit, because a mismatch is a
//    link error on one instruction set on one platform only.
import 'package:flutter_test/flutter_test.dart';

import 'package:qunleashed/pages/tools/subghz/seed/faaccrack_recoverer.dart';
import 'package:qunleashed/pages/tools/subghz/seed/seed_models.dart';

import 'native_sources.dart';

/// The two entries in `keep.txt` that the header does not declare: the engine's
/// own build-time macros. They are the silent case - renamed away, the file
/// still compiles, links and solves while `-DVBITS` and `-DNLF12` quietly stop
/// having any effect.
const _engineOwnMacros = {'VBITS', 'NLF12'};

/// The instruction sets `FAACCRACK_VARIANTS` lists.
List<String> _listedVariants(String header) => RegExp(r'X\((\w+)\)')
    .allMatches(
      RegExp(r'#define FAACCRACK_VARIANTS\(X\)([^\n]*)')
          .firstMatch(header)!
          .group(1)!,
    )
    .map((m) => m.group(1)!)
    .toList(growable: false);

void main() {
  final engine = faaccrackEngine();
  final header = faaccrackHeader();
  final keep = faaccrackKeepList();

  group('the keep list', () {
    test('every name on it still appears in the generated engine', () {
      // The whole point. A name on the list but absent from the engine means
      // either the engine stopped using it, so the list is stale, or a
      // regeneration renamed it anyway - and for VBITS and NLF12 that second
      // case compiles, links, solves, and silently kills a retuning knob.
      final missing = keep.where((name) => !engine.contains(name)).toSet();
      expect(
        missing,
        isEmpty,
        reason:
            'these are in $faaccrackKeepPath but not in $faaccrackEnginePath. '
            'For ${_engineOwnMacros.join(' and ')} this is the silent case: '
            '-D on either would stop having any effect. See '
            '$faaccrackNotesPath.',
      );
    });

    test('carries the engine-owned macros the header does not declare', () {
      // Stated as an assertion so the exception in BUILD_NOTES.md cannot be
      // deleted without this failing.
      expect(keep, containsAll(_engineOwnMacros));
    });
  });

  group('the numbers Dart retypes from the header', () {
    // Every bound and threshold crosses this boundary by being typed out twice,
    // and the two sides fail differently when they disagree. A max that drops
    // in C gives a perfectly good capture "the recovery engine failed"; a
    // confidence threshold that rises in C leaves the app offering a seed the
    // engine's own line says should not be transmitted.
    int macro(String name) {
      final match = RegExp('#define $name\\s+(\\d+)').firstMatch(header);
      if (match == null) {
        throw StateError(
          '$name is not a numeric #define in $faaccrackHeaderPath',
        );
      }
      return int.parse(match.group(1)!);
    }

    test('the hop bounds match', () {
      expect(macro('FAACCRACK_MIN_HOPS'), SeedCapture.minHops);
      expect(macro('FAACCRACK_MAX_HOPS'), SeedCapture.maxHops);
    });

    test('the confidence threshold matches', () {
      expect(macro('FAACCRACK_HOPS_CONFIDENT'), seedHopsConfident);
    });

    test('the mode numbers match', () {
      expect(
        {for (final m in SeedManufacturer.values) m: m.mode},
        {
          SeedManufacturer.faacSlh: macro('FAACCRACK_MODE_FAAC_SLH'),
          SeedManufacturer.bft: macro('FAACCRACK_MODE_BFT'),
          SeedManufacturer.genius: macro('FAACCRACK_MODE_GENIUS'),
          SeedManufacturer.erreka: macro('FAACCRACK_MODE_ERREKA'),
        },
      );
    });

    test('the self-test status range matches', () {
      // The range exists so a fourth check added to the engine still reports as
      // a broken build rather than falling into the generic fault arm, and the
      // Dart side has the two ends written out.
      final enumerated = RegExp(r'FAACCRACK_SELFTEST_\w+ = (-\d+)')
          .allMatches(header)
          .map((m) => int.parse(m.group(1)!))
          .toList();
      expect(enumerated, isNotEmpty);
      expect(
        seedSelfTestFirstStatus,
        enumerated.reduce((a, b) => a < b ? a : b),
      );
      expect(
        seedSelfTestLastStatus,
        enumerated.reduce((a, b) => a > b ? a : b),
      );
    });
  });

  group('the variants the dispatcher selects', () {
    // The assertion this file promised when there was no dispatcher. A variant
    // the CMake compiles and the dispatcher never selects is several-fold
    // slower on that machine with nothing saying so; the reverse is a link
    // error on one instruction set on one platform, found at release.
    final dispatcher = faaccrackDispatcherSource();
    final cmake = faaccrackCMakeSource();

    test('the dispatcher names only variants the header lists', () {
      final listed = _listedVariants(header).toSet();
      final selected = RegExp(r'faaccrack_search_([A-Z][A-Z0-9]*)')
          .allMatches(dispatcher)
          .map((m) => m.group(1)!)
          .toSet();
      expect(selected, isNotEmpty);
      expect(
        selected.difference(listed),
        isEmpty,
        reason: 'the dispatcher references a variant the header does not list',
      );
    });

    test('every variant the dispatcher names is one the build compiles', () {
      final built = RegExp(r'faaccrack_add_variant\((\w+)')
          .allMatches(cmake)
          .map((m) => m.group(1)!)
          .toSet();
      final selected = RegExp(r'faaccrack_search_([A-Z][A-Z0-9]*)')
          .allMatches(dispatcher)
          .map((m) => m.group(1)!)
          .toSet();
      expect(built, isNotEmpty);
      expect(
        selected.difference(built),
        isEmpty,
        reason: 'the dispatcher would reference an object nothing compiles',
      );
      // The other direction, with the one legitimate exception: a variant the
      // dispatcher does not name by hand is still reachable through
      // FAACCRACK_SEARCH on its single-variant path, which is how NEON is
      // selected and how the Apple pod works at all.
      expect(
        dispatcher,
        contains('FAACCRACK_SEARCH'),
        reason:
            'without the single-variant path, a variant the dispatcher '
            'does not name is compiled and never reachable',
      );
      final unreachable = built.difference(selected);
      expect(
        unreachable.length,
        lessThanOrEqualTo(1),
        reason:
            'at most one variant may rely on the single-variant path; '
            '$unreachable do, so some machine silently gets a slower one',
      );
    });

    test('the build says the dispatcher may choose, and the pod does not', () {
      // Losing this define from the CMake is completely silent: all the engine
      // objects still compile and link, and every x86 host quietly runs the
      // baseline one forever.
      expect(cmake, contains('FAACCRACK_MULTI_VARIANT'));
      expect(
        faaccrackPodspecSource(),
        isNot(contains('FAACCRACK_MULTI_VARIANT')),
        reason:
            'the pod compiles one object, so the dispatcher must take its '
            'single-variant path - defining this there is a link error',
      );
    });
  });

  group('the engine exports what the header promises', () {
    test('defines the entry point, non-static, through the macro', () {
      expect(
        RegExp(
          r'^int FAACCRACK_SEARCH\s*\(',
          multiLine: true,
        ).allMatches(engine).length,
        1,
        reason:
            'the ABI entry point is missing or no longer spelled through '
            'FAACCRACK_SEARCH, which is how one source becomes one symbol per '
            'instruction set',
      );
    });

    test('still carries its command-line entry point', () {
      // Not decoration: the author's equivalence script drives the CLI, so
      // losing main() would silently retire the only proof that obfuscating
      // the source did not change what it computes. The library build renames
      // it away with -Dmain=.
      expect(RegExp(r'\bint main\s*\(').allMatches(engine).length, 1);
    });

    test('quote-includes only headers that can be found', () {
      // A quoted include that resolves nowhere is a build failure on one
      // platform only - pthread_shim.h is reached on clang-cl and MSVC alone -
      // so it would otherwise surface on a Windows runner twenty minutes in
      // rather than here in a second.
      expect(
        RegExp(r'#include\s+"([^"]+)"')
            .allMatches(engine)
            .map((m) => m.group(1)!)
            .toSet(),
        faaccrackQuotedIncludes.keys.toSet(),
        reason:
            'the engine quote-includes something this repo has not placed. '
            'Add it to faaccrackQuotedIncludes and put its directory on the '
            "build's include path.",
      );
    });
  });

  group('the variant cascade', () {
    test('selects exactly the instruction sets it lists', () {
      // Both directions against FAACCRACK_VARIANTS rather than against a
      // second hard-coded list here: the macro exists so a sixth instruction
      // set is one edit in one place, and pinning the names again would make
      // it two, the second failing for no reason but the duplicate.
      final listed = _listedVariants(header);
      expect(listed, isNotEmpty);
      final selected = RegExp(
        r'#define FAACCRACK_SEARCH faaccrack_search_(\w+)',
      ).allMatches(header).map((m) => m.group(1)!).toList(growable: false);
      expect(
        selected.toSet(),
        listed.toSet(),
        reason:
            'FAACCRACK_VARIANTS and the #if cascade disagree. A variant listed '
            'but never selected is an object nothing compiles; one selected '
            'but not listed is a symbol no dispatcher will declare.',
      );
    });

    test(
      'an unsupported target fails the build instead of inventing a symbol',
      () {
        // Without this a fall-through platform compiles green - a vector_size
        // type scalarises for any target - and ships a library exporting a name
        // no dispatcher has an entry for.
        expect(header.contains('#error'), isTrue);
      },
    );
  });
}
