// Holds the SubGHz seed-recovery engine, its ABI header and the obfuscator's
// keep list to each other.
//
// The coupling these guard is unusual and easy to break silently. The engine is
// generated by an obfuscator that renames every identifier the source owns
// unless the name is in `keep.txt`. For most names a miss is loud - the engine
// would define a differently-spelled field than the header declares and the
// compile fails - but for `VBITS` and `NLF12` it is not, and those two are why
// this file exists.
//
// What it cannot see:
//
//  * Whether the engine computes the right thing. That is
//    `.github/scripts/check_faaccrack_engine.sh`.
//  * Whether the four FAACCRACK_MODE_* numbers still select the manufacturer
//    the header claims. The engine hard-codes them, so only an end-to-end
//    vector per mode can catch a renumbering - see BUILD_NOTES.md.
//  * Whether a dispatcher names the variants correctly. There is no dispatcher
//    yet; when there is, the assertion that its table matches
//    FAACCRACK_VARIANTS belongs in the same commit, because a mismatch is a
//    link error on one instruction set on one platform only.
import 'package:flutter_test/flutter_test.dart';

import 'faaccrack_sources.dart';

/// Names the header owns that are deliberately absent from `keep.txt`, each
/// with the reason, so that adding a header name forces a decision rather than
/// passing by default.
///
/// The rule the list follows is "every name the engine source spells", not
/// "every name the header owns" - the two are different.
final _exemptFromKeep = <String, String>{
  'faaccrack_status': 'a tag the engine never spells: it uses the enumerators',
  'FAACCRACK_HOPS_CONFIDENT':
      'a policy threshold for callers; the engine has no opinion on it',
  'FAACCRACK_SELFTEST_FIRST': 'a range bound for callers, not a status',
  'FAACCRACK_SELFTEST_LAST': 'a range bound for callers, not a status',
  'FAACCRACK_VARIANTS': 'expanded by the dispatcher, not by the engine',
  'FAACCRACK_LAYOUT_CHANGED': 'the text of a static assertion',
  for (final mode in ['FAAC_SLH', 'BFT', 'GENIUS', 'ERREKA'])
    'FAACCRACK_MODE_$mode': 'the engine hard-codes the mode numbers',
};

/// The two entries in `keep.txt` that the header does not declare: the engine's
/// own build-time macros. They are the silent case - renamed away, the file
/// still compiles, links and solves while `-DVBITS` and `-DNLF12` quietly stop
/// having any effect.
const _engineOwnMacros = {'VBITS', 'NLF12'};

final _definedMacro = RegExp(r'#define\s+(FAACCRACK_\w+)');
final _enumerator = RegExp(r'^\s*(FAACCRACK_\w+)\s*=', multiLine: true);
final _typeTag = RegExp(r'\b(?:struct|enum)\s+(faaccrack_\w+)');
final _structField = RegExp(
  r'^\s*(?:volatile\s+)?uint(?:32|64)_t\s+(\w+);',
  multiLine: true,
);
final _undefined = RegExp(r'#undef\s+(\w+)');

/// The names the header declares that a caller could depend on.
Set<String> _headerNames(String header) {
  final names = {
    for (final pattern in [_definedMacro, _enumerator, _typeTag, _structField])
      ...pattern.allMatches(header).map((m) => m.group(1)!),
  };
  // A macro the header undefines again is scaffolding, not ABI - the X-macro
  // expansion uses one to declare the variants and drops it immediately. Taken
  // from the `#undef`s so the next one costs nothing.
  names.removeAll(_undefined.allMatches(header).map((m) => m.group(1)!));
  return names;
}

/// The instruction sets `FAACCRACK_VARIANTS` lists.
List<String> _listedVariants(String header) => RegExp(r'X\((\w+)\)')
    .allMatches(
      RegExp(r'#define FAACCRACK_VARIANTS\(X\)([^\n]*)')
          .firstMatch(header)!
          .group(1)!,
    )
    .map((m) => m.group(1)!)
    .toList(growable: false);

void main() {
  final engine = faaccrackEngine();
  final header = faaccrackHeader();
  final keep = faaccrackKeepList();
  final headerNames = _headerNames(header);

  group('the keep list', () {
    test('every name on it still appears in the generated engine', () {
      // The whole point. A name on the list but absent from the engine means
      // either the engine stopped using it, so the list is stale, or a
      // regeneration renamed it anyway - and for VBITS and NLF12 that second
      // case compiles, links, solves, and silently kills a retuning knob.
      final missing = keep.where((name) => !engine.contains(name)).toSet();
      expect(
        missing,
        isEmpty,
        reason:
            'these are in $faaccrackKeepPath but not in $faaccrackEnginePath. '
            'For ${_engineOwnMacros.join(' and ')} this is the silent case: '
            '-D on either would stop having any effect. See '
            '$faaccrackNotesPath.',
      );
    });

    test('covers every ABI name the header owns', () {
      expect(
        headerNames
            .where((name) => !keep.contains(name))
            .where((name) => !_exemptFromKeep.containsKey(name))
            .toSet(),
        isEmpty,
        reason:
            'these names are declared in $faaccrackHeaderPath but are neither '
            'in $faaccrackKeepPath nor listed as deliberate exemptions in this '
            'test. Decide which, in the commit that added them.',
      );
    });

    test('carries the engine-owned macros the header does not declare', () {
      // Stated as an assertion so the exception in BUILD_NOTES.md cannot be
      // deleted without this failing.
      expect(keep, containsAll(_engineOwnMacros));
    });

    test('every exemption is still a name the header declares', () {
      // Keeps the exemption map honest: an entry for a name the header no
      // longer has is a stale excuse that would hide a real omission later.
      expect(
        _exemptFromKeep.keys.where((name) => !headerNames.contains(name)),
        isEmpty,
        reason: 'exempted here but $faaccrackHeaderPath no longer declares it',
      );
    });
  });

  group('the engine exports what the header promises', () {
    test('defines the entry point, non-static, through the macro', () {
      expect(
        RegExp(
          r'^int FAACCRACK_SEARCH\s*\(',
          multiLine: true,
        ).allMatches(engine).length,
        1,
        reason:
            'the ABI entry point is missing or no longer spelled through '
            'FAACCRACK_SEARCH, which is how one source becomes one symbol per '
            'instruction set',
      );
    });

    test('still carries its command-line entry point', () {
      // Not decoration: the author's equivalence script drives the CLI, so
      // losing main() would silently retire the only proof that obfuscating
      // the source did not change what it computes. The library build renames
      // it away with -Dmain=.
      expect(RegExp(r'\bint main\s*\(').allMatches(engine).length, 1);
    });

    test('quote-includes only headers that can be found', () {
      // A quoted include that resolves nowhere is a build failure on one
      // platform only - pthread_shim.h is reached on clang-cl and MSVC alone -
      // so it would otherwise surface on a Windows runner twenty minutes in
      // rather than here in a second.
      expect(
        RegExp(r'#include\s+"([^"]+)"')
            .allMatches(engine)
            .map((m) => m.group(1)!)
            .toSet(),
        faaccrackQuotedIncludes.keys.toSet(),
        reason:
            'the engine quote-includes something this repo has not placed. '
            'Add it to faaccrackQuotedIncludes and put its directory on the '
            "build's include path.",
      );
    });
  });

  group('the variant cascade', () {
    test('selects exactly the instruction sets it lists', () {
      // Both directions against FAACCRACK_VARIANTS rather than against a
      // second hard-coded list here: the macro exists so a sixth instruction
      // set is one edit in one place, and pinning the names again would make
      // it two, the second failing for no reason but the duplicate.
      final listed = _listedVariants(header);
      expect(listed, isNotEmpty);
      final selected = RegExp(
        r'#define FAACCRACK_SEARCH faaccrack_search_(\w+)',
      ).allMatches(header).map((m) => m.group(1)!).toList(growable: false);
      expect(
        selected.toSet(),
        listed.toSet(),
        reason:
            'FAACCRACK_VARIANTS and the #if cascade disagree. A variant listed '
            'but never selected is an object nothing compiles; one selected '
            'but not listed is a symbol no dispatcher will declare.',
      );
    });

    test(
      'an unsupported target fails the build instead of inventing a symbol',
      () {
        // Without this a fall-through platform compiles green - a vector_size
        // type scalarises for any target - and ships a library exporting a name
        // no dispatcher has an entry for.
        expect(header.contains('#error'), isTrue);
      },
    );
  });
}
