name: qunleashed
description: "Flipper Zero BLE/USB companion app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flipperlib:
    path: lib/flipperlib
  universal_ble: ^1.0.0
  usb_serial: ^0.5.2
  permission_handler: ^11.3.1
  flutter_libserialport: ^0.6.0
  flutter_svg: ^2.0.10+1
  protobuf: ^6.0.0
  fixnum: ^1.1.1
  saver_gallery: ^4.1.1
  super_clipboard: ^0.9.1
  archive: ^4.0.0
  markdown: ^7.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  file_picker: ^8.1.2
  ffi: ^2.1.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: FlipperBold
      fonts:
        - asset: assets/fonts/flipper_bold.ttf
          weight: 500
  assets:
    - assets/firmware/
    - assets/flipper_svg/
    - assets/flipper_svg/bottombar/
    - assets/flipper_svg/connection/
    - assets/flipper_svg/core/
    - assets/flipper_svg/info/
    - assets/flipper_svg/mockup/
    - assets/flipper_svg/screenstreaming/
    - assets/flipper_svg/tools/
    - assets/flipper_svg/tools/mifare/
    - assets/flipper_svg/archive/
    - assets/apps/
