name: qunleashed
description: "Flipper Zero BLE/USB companion app."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flipperzero:
    path: packages/protobuf
  universal_ble: ^1.0.0
  usb_serial: ^0.5.2
  permission_handler: ^11.3.1
  flutter_libserialport: ^0.6.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: FlipperBold
      fonts:
        - asset: assets/fonts/flipper_bold.ttf
          weight: 500
  assets:
    - assets/firmware_config.json
    - assets/firmware/
    - assets/flipper_svg/
    - assets/flipper_svg/bottombar/
    - assets/flipper_svg/connection/
    - assets/flipper_svg/core/
    - assets/flipper_svg/info/
    - assets/flipper_svg/mockup/
    - assets/flipper_svg/screenstreaming/
