name: qunleashed
description: "Flipper Zero BLE/USB companion app."
homepage: https://aperturefox.ru
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flipperlib:
    path: lib/modules/flipperlib
  universal_ble: ^1.0.0
  usb_serial: ^0.5.2
  permission_handler: ^11.3.1
  flutter_libserialport: ^0.6.0
  flutter_svg: ^2.0.10+1
  protobuf: ^6.0.0
  fixnum: ^1.1.1
  saver_gallery: ^4.1.1
  super_clipboard: ^0.9.1
  archive: ^4.0.0
  markdown: ^7.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  file_picker: ^8.1.2
  ffi: ^2.1.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  flutter_local_notifications: ^21.0.0
  workmanager: ^0.9.0+3
  tray_manager: ^0.5.2
  window_manager: ^0.5.1
  xterm: ^4.0.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: FlipperBold
      fonts:
        - asset: assets/font/flipper-bold.ttf
          weight: 500
    - family: Born2bSportyV2
      fonts:
        - asset: assets/font/born2b-sporty-v2.ttf
    - family: GravityBold8
      fonts:
        - asset: assets/font/gravity-bold-8.ttf
  assets:
    - assets/ic/action/
    - assets/ic/app/
    - assets/ic/connect/
    - assets/ic/control/
    - assets/ic/control/hint/
    - assets/ic/device/
    - assets/ic/file/
    - assets/ic/fileformat/
    - assets/ic/info/
    - assets/ic/nav/
    - assets/ic/state/
    - assets/ic/storage/
    - assets/img/
    - assets/img/firmware/
    - assets/pic/app/
    - assets/pic/device/body/
    - assets/pic/device/screen/
    - assets/pic/mifare/
    - assets/pic/status/
    - assets/pic/tool/
    - LICENSE
